#############################################################################
# Makefile for building: linux-bin/filter-demo
# Generated by qmake (3.1) (Qt 5.9.6)
# Project:  filter-demo.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile filter-demo.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -flto -ffast-math -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -flto -ffast-math -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../../local/include -isystem /usr/include/qt4/qwt -I../../../../include/qt5/qwt -isystem /usr/include/qt4/qwt -isystem /usr/include/qwt -I/usr/local/qwt-6.1.4-svn/ -I../../../../local/include -I../../../../include/qt5 -I../../../../include/qt5/QtWidgets -I../../../../include/qt5/QtGui -I../../../../include/qt5/QtCore -I. -I../../../../include/libdrm -I. -I../../../../lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = filter-demo1.0.0
DISTDIR = /usr/shared/sdr-j-development/systems/filter-demo/.tmp/filter-demo1.0.0
LINK          = g++
LFLAGS        = -flto -Wl,-O1
LIBS          = $(SUBLIBS) -lqwt-qt5 -lusb-1.0 -lrt -lfftw3f -ldl -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		controller.cpp \
		scope.cpp \
		filters.cpp \
		blackman.cpp \
		hann.cpp \
		hamming.cpp \
		blackman-harris.cpp \
		fft.cpp moc_controller.cpp
OBJECTS       = main.o \
		controller.o \
		scope.o \
		filters.o \
		blackman.o \
		hann.o \
		hamming.o \
		blackman-harris.o \
		fft.o \
		moc_controller.o
DIST          = ../../../../lib64/qt5/mkspecs/features/spec_pre.prf \
		../../../../lib64/qt5/mkspecs/common/unix.conf \
		../../../../lib64/qt5/mkspecs/common/linux.conf \
		../../../../lib64/qt5/mkspecs/common/sanitize.conf \
		../../../../lib64/qt5/mkspecs/common/gcc-base.conf \
		../../../../lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../../lib64/qt5/mkspecs/common/g++-base.conf \
		../../../../lib64/qt5/mkspecs/common/g++-unix.conf \
		../../../../lib64/qt5/mkspecs/qconfig.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../lib64/qt5/mkspecs/features/qt_functions.prf \
		../../../../lib64/qt5/mkspecs/features/qt_config.prf \
		../../../../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		../../../../lib64/qt5/mkspecs/features/spec_post.prf \
		../../../../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		../../../../lib64/qt5/mkspecs/features/toolchain.prf \
		../../../../lib64/qt5/mkspecs/features/default_pre.prf \
		../../../../lib64/qt5/mkspecs/features/resolve_config.prf \
		../../../../lib64/qt5/mkspecs/features/default_post.prf \
		../../../../lib64/qt5/mkspecs/features/warn_on.prf \
		../../../../lib64/qt5/mkspecs/features/qt.prf \
		../../../../lib64/qt5/mkspecs/features/resources.prf \
		../../../../lib64/qt5/mkspecs/features/moc.prf \
		../../../../lib64/qt5/mkspecs/features/unix/opengl.prf \
		../../../../lib64/qt5/mkspecs/features/uic.prf \
		../../../../lib64/qt5/mkspecs/features/unix/thread.prf \
		../../../../lib64/qt5/mkspecs/features/qmake_use.prf \
		../../../../lib64/qt5/mkspecs/features/file_copies.prf \
		../../../../lib64/qt5/mkspecs/features/testcase_targets.prf \
		../../../../lib64/qt5/mkspecs/features/exceptions.prf \
		../../../../lib64/qt5/mkspecs/features/yacc.prf \
		../../../../lib64/qt5/mkspecs/features/lex.prf \
		filter-demo.pro controller.h \
		scope.h \
		filters.h \
		blackman.h \
		hann.h \
		hamming.h \
		blackman-harris.h \
		fft.h main.cpp \
		controller.cpp \
		scope.cpp \
		filters.cpp \
		blackman.cpp \
		hann.cpp \
		hamming.cpp \
		blackman-harris.cpp \
		fft.cpp
QMAKE_TARGET  = filter-demo
DESTDIR       = linux-bin/
TARGET        = linux-bin/filter-demo


first: all
####### Build rules

$(TARGET): ui_filter-demo.h $(OBJECTS)  
	@test -d linux-bin/ || mkdir -p linux-bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: filter-demo.pro ../../../../lib64/qt5/mkspecs/linux-g++/qmake.conf ../../../../lib64/qt5/mkspecs/features/spec_pre.prf \
		../../../../lib64/qt5/mkspecs/common/unix.conf \
		../../../../lib64/qt5/mkspecs/common/linux.conf \
		../../../../lib64/qt5/mkspecs/common/sanitize.conf \
		../../../../lib64/qt5/mkspecs/common/gcc-base.conf \
		../../../../lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		../../../../lib64/qt5/mkspecs/common/g++-base.conf \
		../../../../lib64/qt5/mkspecs/common/g++-unix.conf \
		../../../../lib64/qt5/mkspecs/qconfig.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_charts.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../lib64/qt5/mkspecs/features/qt_functions.prf \
		../../../../lib64/qt5/mkspecs/features/qt_config.prf \
		../../../../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		../../../../lib64/qt5/mkspecs/features/spec_post.prf \
		../../../../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		../../../../lib64/qt5/mkspecs/features/toolchain.prf \
		../../../../lib64/qt5/mkspecs/features/default_pre.prf \
		../../../../lib64/qt5/mkspecs/features/resolve_config.prf \
		../../../../lib64/qt5/mkspecs/features/default_post.prf \
		../../../../lib64/qt5/mkspecs/features/warn_on.prf \
		../../../../lib64/qt5/mkspecs/features/qt.prf \
		../../../../lib64/qt5/mkspecs/features/resources.prf \
		../../../../lib64/qt5/mkspecs/features/moc.prf \
		../../../../lib64/qt5/mkspecs/features/unix/opengl.prf \
		../../../../lib64/qt5/mkspecs/features/uic.prf \
		../../../../lib64/qt5/mkspecs/features/unix/thread.prf \
		../../../../lib64/qt5/mkspecs/features/qmake_use.prf \
		../../../../lib64/qt5/mkspecs/features/file_copies.prf \
		../../../../lib64/qt5/mkspecs/features/testcase_targets.prf \
		../../../../lib64/qt5/mkspecs/features/exceptions.prf \
		../../../../lib64/qt5/mkspecs/features/yacc.prf \
		../../../../lib64/qt5/mkspecs/features/lex.prf \
		filter-demo.pro \
		../../../../lib64/libQt5Widgets.prl \
		../../../../lib64/libQt5Gui.prl \
		../../../../lib64/libQt5Core.prl
	$(QMAKE) -o Makefile filter-demo.pro
../../../../lib64/qt5/mkspecs/features/spec_pre.prf:
../../../../lib64/qt5/mkspecs/common/unix.conf:
../../../../lib64/qt5/mkspecs/common/linux.conf:
../../../../lib64/qt5/mkspecs/common/sanitize.conf:
../../../../lib64/qt5/mkspecs/common/gcc-base.conf:
../../../../lib64/qt5/mkspecs/common/gcc-base-unix.conf:
../../../../lib64/qt5/mkspecs/common/g++-base.conf:
../../../../lib64/qt5/mkspecs/common/g++-unix.conf:
../../../../lib64/qt5/mkspecs/qconfig.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3danimation.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dcore.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dextras.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dinput.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquick.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3drender.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_charts.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_charts_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_core.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_enginio.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_help.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_location.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_network.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_script.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandclient.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_webchannel.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../lib64/qt5/mkspecs/features/qt_functions.prf:
../../../../lib64/qt5/mkspecs/features/qt_config.prf:
../../../../lib64/qt5/mkspecs/linux-g++/qmake.conf:
../../../../lib64/qt5/mkspecs/features/spec_post.prf:
../../../../lib64/qt5/mkspecs/features/exclusive_builds.prf:
../../../../lib64/qt5/mkspecs/features/toolchain.prf:
../../../../lib64/qt5/mkspecs/features/default_pre.prf:
../../../../lib64/qt5/mkspecs/features/resolve_config.prf:
../../../../lib64/qt5/mkspecs/features/default_post.prf:
../../../../lib64/qt5/mkspecs/features/warn_on.prf:
../../../../lib64/qt5/mkspecs/features/qt.prf:
../../../../lib64/qt5/mkspecs/features/resources.prf:
../../../../lib64/qt5/mkspecs/features/moc.prf:
../../../../lib64/qt5/mkspecs/features/unix/opengl.prf:
../../../../lib64/qt5/mkspecs/features/uic.prf:
../../../../lib64/qt5/mkspecs/features/unix/thread.prf:
../../../../lib64/qt5/mkspecs/features/qmake_use.prf:
../../../../lib64/qt5/mkspecs/features/file_copies.prf:
../../../../lib64/qt5/mkspecs/features/testcase_targets.prf:
../../../../lib64/qt5/mkspecs/features/exceptions.prf:
../../../../lib64/qt5/mkspecs/features/yacc.prf:
../../../../lib64/qt5/mkspecs/features/lex.prf:
filter-demo.pro:
../../../../lib64/libQt5Widgets.prl:
../../../../lib64/libQt5Gui.prl:
../../../../lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile filter-demo.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents controller.h scope.h filters.h blackman.h hann.h hamming.h blackman-harris.h fft.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp controller.cpp scope.cpp filters.cpp blackman.cpp hann.cpp hamming.cpp blackman-harris.cpp fft.cpp $(DISTDIR)/
	$(COPY_FILE) --parents filter-demo.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -flto -ffast-math -O2 -Wall -W -dM -E -o moc_predefs.h ../../../../lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_controller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_controller.cpp
moc_controller.cpp: ../../../../include/qt5/QtWidgets/QDialog \
		../../../../include/qt5/QtWidgets/qdialog.h \
		../../../../include/qt5/QtWidgets/qtwidgetsglobal.h \
		../../../../include/qt5/QtGui/qtguiglobal.h \
		../../../../include/qt5/QtCore/qglobal.h \
		../../../../include/qt5/QtCore/qconfig-bootstrapped.h \
		../../../../include/qt5/QtCore/qconfig.h \
		../../../../include/qt5/QtCore/qconfig-64.h \
		../../../../include/qt5/QtCore/qtcore-config.h \
		../../../../include/qt5/QtCore/qsystemdetection.h \
		../../../../include/qt5/QtCore/qprocessordetection.h \
		../../../../include/qt5/QtCore/qcompilerdetection.h \
		../../../../include/qt5/QtCore/qtypeinfo.h \
		../../../../include/qt5/QtCore/qsysinfo.h \
		../../../../include/qt5/QtCore/qlogging.h \
		../../../../include/qt5/QtCore/qflags.h \
		../../../../include/qt5/QtCore/qatomic.h \
		../../../../include/qt5/QtCore/qbasicatomic.h \
		../../../../include/qt5/QtCore/qatomic_bootstrap.h \
		../../../../include/qt5/QtCore/qgenericatomic.h \
		../../../../include/qt5/QtCore/qatomic_cxx11.h \
		../../../../include/qt5/QtCore/qatomic_msvc.h \
		../../../../include/qt5/QtCore/qglobalstatic.h \
		../../../../include/qt5/QtCore/qmutex.h \
		../../../../include/qt5/QtCore/qnumeric.h \
		../../../../include/qt5/QtCore/qversiontagging.h \
		../../../../include/qt5/QtGui/qtgui-config.h \
		../../../../include/qt5/QtWidgets/qtwidgets-config.h \
		../../../../include/qt5/QtWidgets/qwidget.h \
		../../../../include/qt5/QtGui/qwindowdefs.h \
		../../../../include/qt5/QtCore/qobjectdefs.h \
		../../../../include/qt5/QtCore/qnamespace.h \
		../../../../include/qt5/QtCore/qobjectdefs_impl.h \
		../../../../include/qt5/QtGui/qwindowdefs_win.h \
		../../../../include/qt5/QtCore/qobject.h \
		../../../../include/qt5/QtCore/qstring.h \
		../../../../include/qt5/QtCore/qchar.h \
		../../../../include/qt5/QtCore/qbytearray.h \
		../../../../include/qt5/QtCore/qrefcount.h \
		../../../../include/qt5/QtCore/qarraydata.h \
		../../../../include/qt5/QtCore/qstringbuilder.h \
		../../../../include/qt5/QtCore/qlist.h \
		../../../../include/qt5/QtCore/qalgorithms.h \
		../../../../include/qt5/QtCore/qiterator.h \
		../../../../include/qt5/QtCore/qhashfunctions.h \
		../../../../include/qt5/QtCore/qpair.h \
		../../../../include/qt5/QtCore/qbytearraylist.h \
		../../../../include/qt5/QtCore/qstringlist.h \
		../../../../include/qt5/QtCore/qregexp.h \
		../../../../include/qt5/QtCore/qstringmatcher.h \
		../../../../include/qt5/QtCore/qcoreevent.h \
		../../../../include/qt5/QtCore/qscopedpointer.h \
		../../../../include/qt5/QtCore/qmetatype.h \
		../../../../include/qt5/QtCore/qvarlengtharray.h \
		../../../../include/qt5/QtCore/qcontainerfwd.h \
		../../../../include/qt5/QtCore/qobject_impl.h \
		../../../../include/qt5/QtCore/qmargins.h \
		../../../../include/qt5/QtGui/qpaintdevice.h \
		../../../../include/qt5/QtCore/qrect.h \
		../../../../include/qt5/QtCore/qsize.h \
		../../../../include/qt5/QtCore/qpoint.h \
		../../../../include/qt5/QtGui/qpalette.h \
		../../../../include/qt5/QtGui/qcolor.h \
		../../../../include/qt5/QtGui/qrgb.h \
		../../../../include/qt5/QtGui/qrgba64.h \
		../../../../include/qt5/QtGui/qbrush.h \
		../../../../include/qt5/QtCore/qvector.h \
		../../../../include/qt5/QtGui/qmatrix.h \
		../../../../include/qt5/QtGui/qpolygon.h \
		../../../../include/qt5/QtGui/qregion.h \
		../../../../include/qt5/QtCore/qdatastream.h \
		../../../../include/qt5/QtCore/qiodevice.h \
		../../../../include/qt5/QtCore/qline.h \
		../../../../include/qt5/QtGui/qtransform.h \
		../../../../include/qt5/QtGui/qpainterpath.h \
		../../../../include/qt5/QtGui/qimage.h \
		../../../../include/qt5/QtGui/qpixelformat.h \
		../../../../include/qt5/QtGui/qpixmap.h \
		../../../../include/qt5/QtCore/qsharedpointer.h \
		../../../../include/qt5/QtCore/qshareddata.h \
		../../../../include/qt5/QtCore/qhash.h \
		../../../../include/qt5/QtCore/qsharedpointer_impl.h \
		../../../../include/qt5/QtGui/qfont.h \
		../../../../include/qt5/QtGui/qfontmetrics.h \
		../../../../include/qt5/QtGui/qfontinfo.h \
		../../../../include/qt5/QtWidgets/qsizepolicy.h \
		../../../../include/qt5/QtGui/qcursor.h \
		../../../../include/qt5/QtGui/qkeysequence.h \
		../../../../include/qt5/QtGui/qevent.h \
		../../../../include/qt5/QtCore/qvariant.h \
		../../../../include/qt5/QtCore/qmap.h \
		../../../../include/qt5/QtCore/qdebug.h \
		../../../../include/qt5/QtCore/qtextstream.h \
		../../../../include/qt5/QtCore/qlocale.h \
		../../../../include/qt5/QtCore/qset.h \
		../../../../include/qt5/QtCore/qcontiguouscache.h \
		../../../../include/qt5/QtCore/qurl.h \
		../../../../include/qt5/QtCore/qurlquery.h \
		../../../../include/qt5/QtCore/qfile.h \
		../../../../include/qt5/QtCore/qfiledevice.h \
		../../../../include/qt5/QtGui/qvector2d.h \
		../../../../include/qt5/QtGui/qtouchdevice.h \
		../../../../include/qt5/QtCore/QStringList \
		../../../../include/qt5/QtWidgets/QComboBox \
		../../../../include/qt5/QtWidgets/qcombobox.h \
		../../../../include/qt5/QtWidgets/qabstractitemdelegate.h \
		../../../../include/qt5/QtWidgets/qstyleoption.h \
		../../../../include/qt5/QtWidgets/qabstractspinbox.h \
		../../../../include/qt5/QtGui/qvalidator.h \
		../../../../include/qt5/QtCore/qregularexpression.h \
		../../../../include/qt5/QtGui/qicon.h \
		../../../../include/qt5/QtWidgets/qslider.h \
		../../../../include/qt5/QtWidgets/qabstractslider.h \
		../../../../include/qt5/QtWidgets/qstyle.h \
		../../../../include/qt5/QtWidgets/qtabbar.h \
		../../../../include/qt5/QtWidgets/qtabwidget.h \
		../../../../include/qt5/QtWidgets/qrubberband.h \
		../../../../include/qt5/QtWidgets/qframe.h \
		../../../../include/qt5/QtCore/qabstractitemmodel.h \
		../../../../include/qt5/QtWidgets/QLabel \
		../../../../include/qt5/QtWidgets/qlabel.h \
		../../../../include/qt5/QtCore/QTimer \
		../../../../include/qt5/QtCore/qtimer.h \
		../../../../include/qt5/QtCore/qbasictimer.h \
		ui_filter-demo.h \
		fft.h \
		controller.h \
		moc_predefs.h \
		../../../../lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/usr/shared/sdr-j-development/systems/filter-demo -I/usr/shared/sdr-j-development/systems/filter-demo -I/usr/local/include -I/usr/include/qt4/qwt -I/usr/include/qt5/qwt -I/usr/include/qt4/qwt -I/usr/include/qwt -I/usr/local/qwt-6.1.4-svn -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include controller.h -o moc_controller.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_filter-demo.h
compiler_uic_clean:
	-$(DEL_FILE) ui_filter-demo.h
ui_filter-demo.h: filter-demo.ui \
		../../../../lib64/qt5/bin/uic \
		../../../../include/qt5/qwt/qwt_plot.h \
		../../../../include/qt5/qwt/qwt_global.h \
		../../../../include/qt5/QtCore/qglobal.h \
		../../../../include/qt5/QtCore/qconfig-bootstrapped.h \
		../../../../include/qt5/QtCore/qconfig.h \
		../../../../include/qt5/QtCore/qconfig-64.h \
		../../../../include/qt5/QtCore/qtcore-config.h \
		../../../../include/qt5/QtCore/qsystemdetection.h \
		../../../../include/qt5/QtCore/qprocessordetection.h \
		../../../../include/qt5/QtCore/qcompilerdetection.h \
		../../../../include/qt5/QtCore/qtypeinfo.h \
		../../../../include/qt5/QtCore/qsysinfo.h \
		../../../../include/qt5/QtCore/qlogging.h \
		../../../../include/qt5/QtCore/qflags.h \
		../../../../include/qt5/QtCore/qatomic.h \
		../../../../include/qt5/QtCore/qbasicatomic.h \
		../../../../include/qt5/QtCore/qatomic_bootstrap.h \
		../../../../include/qt5/QtCore/qgenericatomic.h \
		../../../../include/qt5/QtCore/qatomic_cxx11.h \
		../../../../include/qt5/QtCore/qatomic_msvc.h \
		../../../../include/qt5/QtCore/qglobalstatic.h \
		../../../../include/qt5/QtCore/qmutex.h \
		../../../../include/qt5/QtCore/qnumeric.h \
		../../../../include/qt5/QtCore/qversiontagging.h \
		../../../../include/qt5/qwt/qwt_text.h \
		../../../../include/qt5/QtCore/qstring.h \
		../../../../include/qt5/QtCore/qchar.h \
		../../../../include/qt5/QtCore/qbytearray.h \
		../../../../include/qt5/QtCore/qrefcount.h \
		../../../../include/qt5/QtCore/qnamespace.h \
		../../../../include/qt5/QtCore/qarraydata.h \
		../../../../include/qt5/QtCore/qstringbuilder.h \
		../../../../include/qt5/QtCore/qsize.h \
		../../../../include/qt5/QtGui/qfont.h \
		../../../../include/qt5/QtGui/qtguiglobal.h \
		../../../../include/qt5/QtGui/qtgui-config.h \
		../../../../include/qt5/QtGui/qwindowdefs.h \
		../../../../include/qt5/QtCore/qobjectdefs.h \
		../../../../include/qt5/QtCore/qobjectdefs_impl.h \
		../../../../include/qt5/QtGui/qwindowdefs_win.h \
		../../../../include/qt5/QtCore/qsharedpointer.h \
		../../../../include/qt5/QtCore/qshareddata.h \
		../../../../include/qt5/QtCore/qhash.h \
		../../../../include/qt5/QtCore/qiterator.h \
		../../../../include/qt5/QtCore/qlist.h \
		../../../../include/qt5/QtCore/qalgorithms.h \
		../../../../include/qt5/QtCore/qhashfunctions.h \
		../../../../include/qt5/QtCore/qpair.h \
		../../../../include/qt5/QtCore/qbytearraylist.h \
		../../../../include/qt5/QtCore/qstringlist.h \
		../../../../include/qt5/QtCore/qregexp.h \
		../../../../include/qt5/QtCore/qstringmatcher.h \
		../../../../include/qt5/QtCore/qsharedpointer_impl.h \
		../../../../include/qt5/QtCore/qobject.h \
		../../../../include/qt5/QtCore/qcoreevent.h \
		../../../../include/qt5/QtCore/qscopedpointer.h \
		../../../../include/qt5/QtCore/qmetatype.h \
		../../../../include/qt5/QtCore/qvarlengtharray.h \
		../../../../include/qt5/QtCore/qcontainerfwd.h \
		../../../../include/qt5/QtCore/qobject_impl.h \
		../../../../include/qt5/qwt/qwt_plot_dict.h \
		../../../../include/qt5/qwt/qwt_plot_item.h \
		../../../../include/qt5/qwt/qwt_legend_data.h \
		../../../../include/qt5/qwt/qwt_graphic.h \
		../../../../include/qt5/qwt/qwt_null_paintdevice.h \
		../../../../include/qt5/QtGui/qpaintdevice.h \
		../../../../include/qt5/QtCore/qrect.h \
		../../../../include/qt5/QtCore/qmargins.h \
		../../../../include/qt5/QtCore/qpoint.h \
		../../../../include/qt5/QtGui/qpaintengine.h \
		../../../../include/qt5/QtGui/qpainter.h \
		../../../../include/qt5/QtGui/qpixmap.h \
		../../../../include/qt5/QtGui/qcolor.h \
		../../../../include/qt5/QtGui/qrgb.h \
		../../../../include/qt5/QtGui/qrgba64.h \
		../../../../include/qt5/QtGui/qimage.h \
		../../../../include/qt5/QtGui/qpixelformat.h \
		../../../../include/qt5/QtGui/qtransform.h \
		../../../../include/qt5/QtGui/qmatrix.h \
		../../../../include/qt5/QtGui/qpolygon.h \
		../../../../include/qt5/QtCore/qvector.h \
		../../../../include/qt5/QtGui/qregion.h \
		../../../../include/qt5/QtCore/qdatastream.h \
		../../../../include/qt5/QtCore/qiodevice.h \
		../../../../include/qt5/QtCore/qline.h \
		../../../../include/qt5/QtGui/qpainterpath.h \
		../../../../include/qt5/QtGui/qtextoption.h \
		../../../../include/qt5/QtGui/qpen.h \
		../../../../include/qt5/QtGui/qbrush.h \
		../../../../include/qt5/QtGui/qfontinfo.h \
		../../../../include/qt5/QtGui/qfontmetrics.h \
		../../../../include/qt5/QtCore/qvariant.h \
		../../../../include/qt5/QtCore/qmap.h \
		../../../../include/qt5/QtCore/qdebug.h \
		../../../../include/qt5/QtCore/qtextstream.h \
		../../../../include/qt5/QtCore/qlocale.h \
		../../../../include/qt5/QtCore/qset.h \
		../../../../include/qt5/QtCore/qcontiguouscache.h \
		../../../../include/qt5/qwt/qwt_scale_map.h \
		../../../../include/qt5/qwt/qwt_transform.h \
		../../../../include/qt5/qwt/qwt_interval.h \
		../../../../include/qt5/QtWidgets/qframe.h \
		../../../../include/qt5/QtWidgets/qtwidgetsglobal.h \
		../../../../include/qt5/QtWidgets/qtwidgets-config.h \
		../../../../include/qt5/QtWidgets/qwidget.h \
		../../../../include/qt5/QtGui/qpalette.h \
		../../../../include/qt5/QtWidgets/qsizepolicy.h \
		../../../../include/qt5/QtGui/qcursor.h \
		../../../../include/qt5/QtGui/qkeysequence.h \
		../../../../include/qt5/QtGui/qevent.h \
		../../../../include/qt5/QtCore/qurl.h \
		../../../../include/qt5/QtCore/qurlquery.h \
		../../../../include/qt5/QtCore/qfile.h \
		../../../../include/qt5/QtCore/qfiledevice.h \
		../../../../include/qt5/QtGui/qvector2d.h \
		../../../../include/qt5/QtGui/qtouchdevice.h
	/usr/lib64/qt5/bin/uic filter-demo.ui -o ui_filter-demo.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ../../../../include/qt5/QtCore/Qt \
		../../../../include/qt5/QtCore/qnamespace.h \
		../../../../include/qt5/QtCore/qglobal.h \
		../../../../include/qt5/QtCore/qconfig-bootstrapped.h \
		../../../../include/qt5/QtCore/qconfig.h \
		../../../../include/qt5/QtCore/qconfig-64.h \
		../../../../include/qt5/QtCore/qtcore-config.h \
		../../../../include/qt5/QtCore/qsystemdetection.h \
		../../../../include/qt5/QtCore/qprocessordetection.h \
		../../../../include/qt5/QtCore/qcompilerdetection.h \
		../../../../include/qt5/QtCore/qtypeinfo.h \
		../../../../include/qt5/QtCore/qsysinfo.h \
		../../../../include/qt5/QtCore/qlogging.h \
		../../../../include/qt5/QtCore/qflags.h \
		../../../../include/qt5/QtCore/qatomic.h \
		../../../../include/qt5/QtCore/qbasicatomic.h \
		../../../../include/qt5/QtCore/qatomic_bootstrap.h \
		../../../../include/qt5/QtCore/qgenericatomic.h \
		../../../../include/qt5/QtCore/qatomic_cxx11.h \
		../../../../include/qt5/QtCore/qatomic_msvc.h \
		../../../../include/qt5/QtCore/qglobalstatic.h \
		../../../../include/qt5/QtCore/qmutex.h \
		../../../../include/qt5/QtCore/qnumeric.h \
		../../../../include/qt5/QtCore/qversiontagging.h \
		../../../../include/qt5/QtWidgets/QApplication \
		../../../../include/qt5/QtWidgets/qapplication.h \
		../../../../include/qt5/QtWidgets/qtwidgetsglobal.h \
		../../../../include/qt5/QtGui/qtguiglobal.h \
		../../../../include/qt5/QtGui/qtgui-config.h \
		../../../../include/qt5/QtWidgets/qtwidgets-config.h \
		../../../../include/qt5/QtCore/qcoreapplication.h \
		../../../../include/qt5/QtCore/qstring.h \
		../../../../include/qt5/QtCore/qchar.h \
		../../../../include/qt5/QtCore/qbytearray.h \
		../../../../include/qt5/QtCore/qrefcount.h \
		../../../../include/qt5/QtCore/qarraydata.h \
		../../../../include/qt5/QtCore/qstringbuilder.h \
		../../../../include/qt5/QtCore/qobject.h \
		../../../../include/qt5/QtCore/qobjectdefs.h \
		../../../../include/qt5/QtCore/qobjectdefs_impl.h \
		../../../../include/qt5/QtCore/qlist.h \
		../../../../include/qt5/QtCore/qalgorithms.h \
		../../../../include/qt5/QtCore/qiterator.h \
		../../../../include/qt5/QtCore/qhashfunctions.h \
		../../../../include/qt5/QtCore/qpair.h \
		../../../../include/qt5/QtCore/qbytearraylist.h \
		../../../../include/qt5/QtCore/qstringlist.h \
		../../../../include/qt5/QtCore/qregexp.h \
		../../../../include/qt5/QtCore/qstringmatcher.h \
		../../../../include/qt5/QtCore/qcoreevent.h \
		../../../../include/qt5/QtCore/qscopedpointer.h \
		../../../../include/qt5/QtCore/qmetatype.h \
		../../../../include/qt5/QtCore/qvarlengtharray.h \
		../../../../include/qt5/QtCore/qcontainerfwd.h \
		../../../../include/qt5/QtCore/qobject_impl.h \
		../../../../include/qt5/QtCore/qeventloop.h \
		../../../../include/qt5/QtGui/qwindowdefs.h \
		../../../../include/qt5/QtGui/qwindowdefs_win.h \
		../../../../include/qt5/QtCore/qpoint.h \
		../../../../include/qt5/QtCore/qsize.h \
		../../../../include/qt5/QtGui/qcursor.h \
		../../../../include/qt5/QtWidgets/qdesktopwidget.h \
		../../../../include/qt5/QtWidgets/qwidget.h \
		../../../../include/qt5/QtCore/qmargins.h \
		../../../../include/qt5/QtGui/qpaintdevice.h \
		../../../../include/qt5/QtCore/qrect.h \
		../../../../include/qt5/QtGui/qpalette.h \
		../../../../include/qt5/QtGui/qcolor.h \
		../../../../include/qt5/QtGui/qrgb.h \
		../../../../include/qt5/QtGui/qrgba64.h \
		../../../../include/qt5/QtGui/qbrush.h \
		../../../../include/qt5/QtCore/qvector.h \
		../../../../include/qt5/QtGui/qmatrix.h \
		../../../../include/qt5/QtGui/qpolygon.h \
		../../../../include/qt5/QtGui/qregion.h \
		../../../../include/qt5/QtCore/qdatastream.h \
		../../../../include/qt5/QtCore/qiodevice.h \
		../../../../include/qt5/QtCore/qline.h \
		../../../../include/qt5/QtGui/qtransform.h \
		../../../../include/qt5/QtGui/qpainterpath.h \
		../../../../include/qt5/QtGui/qimage.h \
		../../../../include/qt5/QtGui/qpixelformat.h \
		../../../../include/qt5/QtGui/qpixmap.h \
		../../../../include/qt5/QtCore/qsharedpointer.h \
		../../../../include/qt5/QtCore/qshareddata.h \
		../../../../include/qt5/QtCore/qhash.h \
		../../../../include/qt5/QtCore/qsharedpointer_impl.h \
		../../../../include/qt5/QtGui/qfont.h \
		../../../../include/qt5/QtGui/qfontmetrics.h \
		../../../../include/qt5/QtGui/qfontinfo.h \
		../../../../include/qt5/QtWidgets/qsizepolicy.h \
		../../../../include/qt5/QtGui/qkeysequence.h \
		../../../../include/qt5/QtGui/qevent.h \
		../../../../include/qt5/QtCore/qvariant.h \
		../../../../include/qt5/QtCore/qmap.h \
		../../../../include/qt5/QtCore/qdebug.h \
		../../../../include/qt5/QtCore/qtextstream.h \
		../../../../include/qt5/QtCore/qlocale.h \
		../../../../include/qt5/QtCore/qset.h \
		../../../../include/qt5/QtCore/qcontiguouscache.h \
		../../../../include/qt5/QtCore/qurl.h \
		../../../../include/qt5/QtCore/qurlquery.h \
		../../../../include/qt5/QtCore/qfile.h \
		../../../../include/qt5/QtCore/qfiledevice.h \
		../../../../include/qt5/QtGui/qvector2d.h \
		../../../../include/qt5/QtGui/qtouchdevice.h \
		../../../../include/qt5/QtGui/qguiapplication.h \
		../../../../include/qt5/QtGui/qinputmethod.h \
		../../../../include/qt5/QtCore/QSettings \
		../../../../include/qt5/QtCore/qsettings.h \
		../../../../include/qt5/QtCore/QDir \
		../../../../include/qt5/QtCore/qdir.h \
		../../../../include/qt5/QtCore/qfileinfo.h \
		controller.h \
		../../../../include/qt5/QtWidgets/QDialog \
		../../../../include/qt5/QtWidgets/qdialog.h \
		../../../../include/qt5/QtCore/QStringList \
		../../../../include/qt5/QtWidgets/QComboBox \
		../../../../include/qt5/QtWidgets/qcombobox.h \
		../../../../include/qt5/QtWidgets/qabstractitemdelegate.h \
		../../../../include/qt5/QtWidgets/qstyleoption.h \
		../../../../include/qt5/QtWidgets/qabstractspinbox.h \
		../../../../include/qt5/QtGui/qvalidator.h \
		../../../../include/qt5/QtCore/qregularexpression.h \
		../../../../include/qt5/QtGui/qicon.h \
		../../../../include/qt5/QtWidgets/qslider.h \
		../../../../include/qt5/QtWidgets/qabstractslider.h \
		../../../../include/qt5/QtWidgets/qstyle.h \
		../../../../include/qt5/QtWidgets/qtabbar.h \
		../../../../include/qt5/QtWidgets/qtabwidget.h \
		../../../../include/qt5/QtWidgets/qrubberband.h \
		../../../../include/qt5/QtWidgets/qframe.h \
		../../../../include/qt5/QtCore/qabstractitemmodel.h \
		../../../../include/qt5/QtWidgets/QLabel \
		../../../../include/qt5/QtWidgets/qlabel.h \
		../../../../include/qt5/QtCore/QTimer \
		../../../../include/qt5/QtCore/qtimer.h \
		../../../../include/qt5/QtCore/qbasictimer.h \
		ui_filter-demo.h \
		fft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

controller.o: controller.cpp controller.h \
		../../../../include/qt5/QtWidgets/QDialog \
		../../../../include/qt5/QtWidgets/qdialog.h \
		../../../../include/qt5/QtWidgets/qtwidgetsglobal.h \
		../../../../include/qt5/QtGui/qtguiglobal.h \
		../../../../include/qt5/QtCore/qglobal.h \
		../../../../include/qt5/QtCore/qconfig-bootstrapped.h \
		../../../../include/qt5/QtCore/qconfig.h \
		../../../../include/qt5/QtCore/qconfig-64.h \
		../../../../include/qt5/QtCore/qtcore-config.h \
		../../../../include/qt5/QtCore/qsystemdetection.h \
		../../../../include/qt5/QtCore/qprocessordetection.h \
		../../../../include/qt5/QtCore/qcompilerdetection.h \
		../../../../include/qt5/QtCore/qtypeinfo.h \
		../../../../include/qt5/QtCore/qsysinfo.h \
		../../../../include/qt5/QtCore/qlogging.h \
		../../../../include/qt5/QtCore/qflags.h \
		../../../../include/qt5/QtCore/qatomic.h \
		../../../../include/qt5/QtCore/qbasicatomic.h \
		../../../../include/qt5/QtCore/qatomic_bootstrap.h \
		../../../../include/qt5/QtCore/qgenericatomic.h \
		../../../../include/qt5/QtCore/qatomic_cxx11.h \
		../../../../include/qt5/QtCore/qatomic_msvc.h \
		../../../../include/qt5/QtCore/qglobalstatic.h \
		../../../../include/qt5/QtCore/qmutex.h \
		../../../../include/qt5/QtCore/qnumeric.h \
		../../../../include/qt5/QtCore/qversiontagging.h \
		../../../../include/qt5/QtGui/qtgui-config.h \
		../../../../include/qt5/QtWidgets/qtwidgets-config.h \
		../../../../include/qt5/QtWidgets/qwidget.h \
		../../../../include/qt5/QtGui/qwindowdefs.h \
		../../../../include/qt5/QtCore/qobjectdefs.h \
		../../../../include/qt5/QtCore/qnamespace.h \
		../../../../include/qt5/QtCore/qobjectdefs_impl.h \
		../../../../include/qt5/QtGui/qwindowdefs_win.h \
		../../../../include/qt5/QtCore/qobject.h \
		../../../../include/qt5/QtCore/qstring.h \
		../../../../include/qt5/QtCore/qchar.h \
		../../../../include/qt5/QtCore/qbytearray.h \
		../../../../include/qt5/QtCore/qrefcount.h \
		../../../../include/qt5/QtCore/qarraydata.h \
		../../../../include/qt5/QtCore/qstringbuilder.h \
		../../../../include/qt5/QtCore/qlist.h \
		../../../../include/qt5/QtCore/qalgorithms.h \
		../../../../include/qt5/QtCore/qiterator.h \
		../../../../include/qt5/QtCore/qhashfunctions.h \
		../../../../include/qt5/QtCore/qpair.h \
		../../../../include/qt5/QtCore/qbytearraylist.h \
		../../../../include/qt5/QtCore/qstringlist.h \
		../../../../include/qt5/QtCore/qregexp.h \
		../../../../include/qt5/QtCore/qstringmatcher.h \
		../../../../include/qt5/QtCore/qcoreevent.h \
		../../../../include/qt5/QtCore/qscopedpointer.h \
		../../../../include/qt5/QtCore/qmetatype.h \
		../../../../include/qt5/QtCore/qvarlengtharray.h \
		../../../../include/qt5/QtCore/qcontainerfwd.h \
		../../../../include/qt5/QtCore/qobject_impl.h \
		../../../../include/qt5/QtCore/qmargins.h \
		../../../../include/qt5/QtGui/qpaintdevice.h \
		../../../../include/qt5/QtCore/qrect.h \
		../../../../include/qt5/QtCore/qsize.h \
		../../../../include/qt5/QtCore/qpoint.h \
		../../../../include/qt5/QtGui/qpalette.h \
		../../../../include/qt5/QtGui/qcolor.h \
		../../../../include/qt5/QtGui/qrgb.h \
		../../../../include/qt5/QtGui/qrgba64.h \
		../../../../include/qt5/QtGui/qbrush.h \
		../../../../include/qt5/QtCore/qvector.h \
		../../../../include/qt5/QtGui/qmatrix.h \
		../../../../include/qt5/QtGui/qpolygon.h \
		../../../../include/qt5/QtGui/qregion.h \
		../../../../include/qt5/QtCore/qdatastream.h \
		../../../../include/qt5/QtCore/qiodevice.h \
		../../../../include/qt5/QtCore/qline.h \
		../../../../include/qt5/QtGui/qtransform.h \
		../../../../include/qt5/QtGui/qpainterpath.h \
		../../../../include/qt5/QtGui/qimage.h \
		../../../../include/qt5/QtGui/qpixelformat.h \
		../../../../include/qt5/QtGui/qpixmap.h \
		../../../../include/qt5/QtCore/qsharedpointer.h \
		../../../../include/qt5/QtCore/qshareddata.h \
		../../../../include/qt5/QtCore/qhash.h \
		../../../../include/qt5/QtCore/qsharedpointer_impl.h \
		../../../../include/qt5/QtGui/qfont.h \
		../../../../include/qt5/QtGui/qfontmetrics.h \
		../../../../include/qt5/QtGui/qfontinfo.h \
		../../../../include/qt5/QtWidgets/qsizepolicy.h \
		../../../../include/qt5/QtGui/qcursor.h \
		../../../../include/qt5/QtGui/qkeysequence.h \
		../../../../include/qt5/QtGui/qevent.h \
		../../../../include/qt5/QtCore/qvariant.h \
		../../../../include/qt5/QtCore/qmap.h \
		../../../../include/qt5/QtCore/qdebug.h \
		../../../../include/qt5/QtCore/qtextstream.h \
		../../../../include/qt5/QtCore/qlocale.h \
		../../../../include/qt5/QtCore/qset.h \
		../../../../include/qt5/QtCore/qcontiguouscache.h \
		../../../../include/qt5/QtCore/qurl.h \
		../../../../include/qt5/QtCore/qurlquery.h \
		../../../../include/qt5/QtCore/qfile.h \
		../../../../include/qt5/QtCore/qfiledevice.h \
		../../../../include/qt5/QtGui/qvector2d.h \
		../../../../include/qt5/QtGui/qtouchdevice.h \
		../../../../include/qt5/QtCore/QStringList \
		../../../../include/qt5/QtWidgets/QComboBox \
		../../../../include/qt5/QtWidgets/qcombobox.h \
		../../../../include/qt5/QtWidgets/qabstractitemdelegate.h \
		../../../../include/qt5/QtWidgets/qstyleoption.h \
		../../../../include/qt5/QtWidgets/qabstractspinbox.h \
		../../../../include/qt5/QtGui/qvalidator.h \
		../../../../include/qt5/QtCore/qregularexpression.h \
		../../../../include/qt5/QtGui/qicon.h \
		../../../../include/qt5/QtWidgets/qslider.h \
		../../../../include/qt5/QtWidgets/qabstractslider.h \
		../../../../include/qt5/QtWidgets/qstyle.h \
		../../../../include/qt5/QtWidgets/qtabbar.h \
		../../../../include/qt5/QtWidgets/qtabwidget.h \
		../../../../include/qt5/QtWidgets/qrubberband.h \
		../../../../include/qt5/QtWidgets/qframe.h \
		../../../../include/qt5/QtCore/qabstractitemmodel.h \
		../../../../include/qt5/QtWidgets/QLabel \
		../../../../include/qt5/QtWidgets/qlabel.h \
		../../../../include/qt5/QtCore/QTimer \
		../../../../include/qt5/QtCore/qtimer.h \
		../../../../include/qt5/QtCore/qbasictimer.h \
		ui_filter-demo.h \
		fft.h \
		blackman.h \
		filters.h \
		hann.h \
		hamming.h \
		blackman-harris.h \
		scope.h \
		../../../../include/qt5/qwt/qwt.h \
		../../../../include/qt5/qwt/qwt_global.h \
		../../../../include/qt5/qwt/qwt_plot.h \
		../../../../include/qt5/qwt/qwt_text.h \
		../../../../include/qt5/qwt/qwt_plot_dict.h \
		../../../../include/qt5/qwt/qwt_plot_item.h \
		../../../../include/qt5/qwt/qwt_legend_data.h \
		../../../../include/qt5/qwt/qwt_graphic.h \
		../../../../include/qt5/qwt/qwt_null_paintdevice.h \
		../../../../include/qt5/QtGui/qpaintengine.h \
		../../../../include/qt5/QtGui/qpainter.h \
		../../../../include/qt5/QtGui/qtextoption.h \
		../../../../include/qt5/QtGui/qpen.h \
		../../../../include/qt5/qwt/qwt_scale_map.h \
		../../../../include/qt5/qwt/qwt_transform.h \
		../../../../include/qt5/qwt/qwt_interval.h \
		../../../../include/qt5/qwt/qwt_plot_marker.h \
		../../../../include/qt5/qwt/qwt_plot_grid.h \
		../../../../include/qt5/qwt/qwt_scale_div.h \
		../../../../include/qt5/qwt/qwt_plot_curve.h \
		../../../../include/qt5/qwt/qwt_plot_seriesitem.h \
		../../../../include/qt5/qwt/qwt_series_data.h \
		../../../../include/qt5/qwt/qwt_samples.h \
		../../../../include/qt5/qwt/qwt_point_3d.h \
		../../../../include/qt5/qwt/qwt_point_polar.h \
		../../../../include/qt5/qwt/qwt_math.h \
		../../../../include/qt5/QtCore/qmath.h \
		../../../../include/qt5/qwt/qwt_series_store.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

scope.o: scope.cpp scope.h \
		../../../../include/qt5/qwt/qwt.h \
		../../../../include/qt5/qwt/qwt_global.h \
		../../../../include/qt5/QtCore/qglobal.h \
		../../../../include/qt5/QtCore/qconfig-bootstrapped.h \
		../../../../include/qt5/QtCore/qconfig.h \
		../../../../include/qt5/QtCore/qconfig-64.h \
		../../../../include/qt5/QtCore/qtcore-config.h \
		../../../../include/qt5/QtCore/qsystemdetection.h \
		../../../../include/qt5/QtCore/qprocessordetection.h \
		../../../../include/qt5/QtCore/qcompilerdetection.h \
		../../../../include/qt5/QtCore/qtypeinfo.h \
		../../../../include/qt5/QtCore/qsysinfo.h \
		../../../../include/qt5/QtCore/qlogging.h \
		../../../../include/qt5/QtCore/qflags.h \
		../../../../include/qt5/QtCore/qatomic.h \
		../../../../include/qt5/QtCore/qbasicatomic.h \
		../../../../include/qt5/QtCore/qatomic_bootstrap.h \
		../../../../include/qt5/QtCore/qgenericatomic.h \
		../../../../include/qt5/QtCore/qatomic_cxx11.h \
		../../../../include/qt5/QtCore/qatomic_msvc.h \
		../../../../include/qt5/QtCore/qglobalstatic.h \
		../../../../include/qt5/QtCore/qmutex.h \
		../../../../include/qt5/QtCore/qnumeric.h \
		../../../../include/qt5/QtCore/qversiontagging.h \
		../../../../include/qt5/qwt/qwt_plot.h \
		../../../../include/qt5/qwt/qwt_text.h \
		../../../../include/qt5/QtCore/qstring.h \
		../../../../include/qt5/QtCore/qchar.h \
		../../../../include/qt5/QtCore/qbytearray.h \
		../../../../include/qt5/QtCore/qrefcount.h \
		../../../../include/qt5/QtCore/qnamespace.h \
		../../../../include/qt5/QtCore/qarraydata.h \
		../../../../include/qt5/QtCore/qstringbuilder.h \
		../../../../include/qt5/QtCore/qsize.h \
		../../../../include/qt5/QtGui/qfont.h \
		../../../../include/qt5/QtGui/qtguiglobal.h \
		../../../../include/qt5/QtGui/qtgui-config.h \
		../../../../include/qt5/QtGui/qwindowdefs.h \
		../../../../include/qt5/QtCore/qobjectdefs.h \
		../../../../include/qt5/QtCore/qobjectdefs_impl.h \
		../../../../include/qt5/QtGui/qwindowdefs_win.h \
		../../../../include/qt5/QtCore/qsharedpointer.h \
		../../../../include/qt5/QtCore/qshareddata.h \
		../../../../include/qt5/QtCore/qhash.h \
		../../../../include/qt5/QtCore/qiterator.h \
		../../../../include/qt5/QtCore/qlist.h \
		../../../../include/qt5/QtCore/qalgorithms.h \
		../../../../include/qt5/QtCore/qhashfunctions.h \
		../../../../include/qt5/QtCore/qpair.h \
		../../../../include/qt5/QtCore/qbytearraylist.h \
		../../../../include/qt5/QtCore/qstringlist.h \
		../../../../include/qt5/QtCore/qregexp.h \
		../../../../include/qt5/QtCore/qstringmatcher.h \
		../../../../include/qt5/QtCore/qsharedpointer_impl.h \
		../../../../include/qt5/QtCore/qobject.h \
		../../../../include/qt5/QtCore/qcoreevent.h \
		../../../../include/qt5/QtCore/qscopedpointer.h \
		../../../../include/qt5/QtCore/qmetatype.h \
		../../../../include/qt5/QtCore/qvarlengtharray.h \
		../../../../include/qt5/QtCore/qcontainerfwd.h \
		../../../../include/qt5/QtCore/qobject_impl.h \
		../../../../include/qt5/qwt/qwt_plot_dict.h \
		../../../../include/qt5/qwt/qwt_plot_item.h \
		../../../../include/qt5/qwt/qwt_legend_data.h \
		../../../../include/qt5/qwt/qwt_graphic.h \
		../../../../include/qt5/qwt/qwt_null_paintdevice.h \
		../../../../include/qt5/QtGui/qpaintdevice.h \
		../../../../include/qt5/QtCore/qrect.h \
		../../../../include/qt5/QtCore/qmargins.h \
		../../../../include/qt5/QtCore/qpoint.h \
		../../../../include/qt5/QtGui/qpaintengine.h \
		../../../../include/qt5/QtGui/qpainter.h \
		../../../../include/qt5/QtGui/qpixmap.h \
		../../../../include/qt5/QtGui/qcolor.h \
		../../../../include/qt5/QtGui/qrgb.h \
		../../../../include/qt5/QtGui/qrgba64.h \
		../../../../include/qt5/QtGui/qimage.h \
		../../../../include/qt5/QtGui/qpixelformat.h \
		../../../../include/qt5/QtGui/qtransform.h \
		../../../../include/qt5/QtGui/qmatrix.h \
		../../../../include/qt5/QtGui/qpolygon.h \
		../../../../include/qt5/QtCore/qvector.h \
		../../../../include/qt5/QtGui/qregion.h \
		../../../../include/qt5/QtCore/qdatastream.h \
		../../../../include/qt5/QtCore/qiodevice.h \
		../../../../include/qt5/QtCore/qline.h \
		../../../../include/qt5/QtGui/qpainterpath.h \
		../../../../include/qt5/QtGui/qtextoption.h \
		../../../../include/qt5/QtGui/qpen.h \
		../../../../include/qt5/QtGui/qbrush.h \
		../../../../include/qt5/QtGui/qfontinfo.h \
		../../../../include/qt5/QtGui/qfontmetrics.h \
		../../../../include/qt5/QtCore/qvariant.h \
		../../../../include/qt5/QtCore/qmap.h \
		../../../../include/qt5/QtCore/qdebug.h \
		../../../../include/qt5/QtCore/qtextstream.h \
		../../../../include/qt5/QtCore/qlocale.h \
		../../../../include/qt5/QtCore/qset.h \
		../../../../include/qt5/QtCore/qcontiguouscache.h \
		../../../../include/qt5/qwt/qwt_scale_map.h \
		../../../../include/qt5/qwt/qwt_transform.h \
		../../../../include/qt5/qwt/qwt_interval.h \
		../../../../include/qt5/QtWidgets/qframe.h \
		../../../../include/qt5/QtWidgets/qtwidgetsglobal.h \
		../../../../include/qt5/QtWidgets/qtwidgets-config.h \
		../../../../include/qt5/QtWidgets/qwidget.h \
		../../../../include/qt5/QtGui/qpalette.h \
		../../../../include/qt5/QtWidgets/qsizepolicy.h \
		../../../../include/qt5/QtGui/qcursor.h \
		../../../../include/qt5/QtGui/qkeysequence.h \
		../../../../include/qt5/QtGui/qevent.h \
		../../../../include/qt5/QtCore/qurl.h \
		../../../../include/qt5/QtCore/qurlquery.h \
		../../../../include/qt5/QtCore/qfile.h \
		../../../../include/qt5/QtCore/qfiledevice.h \
		../../../../include/qt5/QtGui/qvector2d.h \
		../../../../include/qt5/QtGui/qtouchdevice.h \
		../../../../include/qt5/qwt/qwt_plot_marker.h \
		../../../../include/qt5/qwt/qwt_plot_grid.h \
		../../../../include/qt5/qwt/qwt_scale_div.h \
		../../../../include/qt5/qwt/qwt_plot_curve.h \
		../../../../include/qt5/qwt/qwt_plot_seriesitem.h \
		../../../../include/qt5/qwt/qwt_series_data.h \
		../../../../include/qt5/qwt/qwt_samples.h \
		../../../../include/qt5/qwt/qwt_point_3d.h \
		../../../../include/qt5/qwt/qwt_point_polar.h \
		../../../../include/qt5/qwt/qwt_math.h \
		../../../../include/qt5/QtCore/qmath.h \
		../../../../include/qt5/qwt/qwt_series_store.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scope.o scope.cpp

filters.o: filters.cpp filters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filters.o filters.cpp

blackman.o: blackman.cpp blackman.h \
		filters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blackman.o blackman.cpp

hann.o: hann.cpp hann.h \
		filters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hann.o hann.cpp

hamming.o: hamming.cpp hamming.h \
		filters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hamming.o hamming.cpp

blackman-harris.o: blackman-harris.cpp blackman-harris.h \
		filters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blackman-harris.o blackman-harris.cpp

fft.o: fft.cpp fft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fft.o fft.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

